name: Deployment_Pipeline
on: [push]

# better to have different environments (node/python) on different jobs
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - id: s00
        run: echo "Repository is ${{ github.repository }}"
      - id: s01
        # Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'
      - run: echo "Before:" && ls -l
      - id: s02
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
      - run: echo "After:" && ls -l
      - id: s03
        # install Angular
        run: |
          npm i -g @angular/cli
          npm ci
          echo "Installed"
      # - id: s04
      #   run: |
      #     echo "Faking an error"
      #     exit 1
      - id: s05
        # build the Angular app
        run: |
          ng build
          echo "Built"
      # monitor distribution files
      - run: echo "Distribution files:" && ls -l dist/countingbook/browser
      - id:
          s06
          # deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: dist/countingbook/browser
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
